// <auto-generated>
//     Generated by the protocol buffer compiler.
//     source: Square/protos/square.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Example.Grpc {
  public static partial class SquareService
  {
    static readonly string __ServiceName = "com.example.grpc.SquareService";

    static readonly grpc::Marshaller<global::Com.Example.Grpc.SquareRequest> __Marshaller_com_example_grpc_SquareRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Example.Grpc.SquareRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Com.Example.Grpc.SquareResponse> __Marshaller_com_example_grpc_SquareResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Example.Grpc.SquareResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Com.Example.Grpc.SquareRequest, global::Com.Example.Grpc.SquareResponse> __Method_getSquare = new grpc::Method<global::Com.Example.Grpc.SquareRequest, global::Com.Example.Grpc.SquareResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getSquare",
        __Marshaller_com_example_grpc_SquareRequest,
        __Marshaller_com_example_grpc_SquareResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Example.Grpc.SquareReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SquareService</summary>
    public abstract partial class SquareServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Com.Example.Grpc.SquareResponse> getSquare(global::Com.Example.Grpc.SquareRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SquareService</summary>
    public partial class SquareServiceClient : grpc::ClientBase<SquareServiceClient>
    {
      /// <summary>Creates a new client for SquareService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SquareServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SquareService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SquareServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SquareServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SquareServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Com.Example.Grpc.SquareResponse getSquare(global::Com.Example.Grpc.SquareRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getSquare(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Com.Example.Grpc.SquareResponse getSquare(global::Com.Example.Grpc.SquareRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getSquare, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Grpc.SquareResponse> getSquareAsync(global::Com.Example.Grpc.SquareRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getSquareAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Grpc.SquareResponse> getSquareAsync(global::Com.Example.Grpc.SquareRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getSquare, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SquareServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SquareServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SquareServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_getSquare, serviceImpl.getSquare).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SquareServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_getSquare, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Com.Example.Grpc.SquareRequest, global::Com.Example.Grpc.SquareResponse>(serviceImpl.getSquare));
    }

  }
}
#endregion
